// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file power.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "power.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define power_max_cdr_typesize 264ULL;
#define power_max_key_cdr_typesize 0ULL;

power::power()
{
    // unsigned long m_freq
    m_freq = 0;
    // string m_message
    m_message ="";

}

power::~power()
{


}

power::power(
        const power& x)
{
    m_freq = x.m_freq;
    m_message = x.m_message;
}

power::power(
        power&& x) noexcept 
{
    m_freq = x.m_freq;
    m_message = std::move(x.m_message);
}

power& power::operator =(
        const power& x)
{

    m_freq = x.m_freq;
    m_message = x.m_message;

    return *this;
}

power& power::operator =(
        power&& x) noexcept
{

    m_freq = x.m_freq;
    m_message = std::move(x.m_message);

    return *this;
}

bool power::operator ==(
        const power& x) const
{

    return (m_freq == x.m_freq && m_message == x.m_message);
}

bool power::operator !=(
        const power& x) const
{
    return !(*this == x);
}

size_t power::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return power_max_cdr_typesize;
}

size_t power::getCdrSerializedSize(
        const power& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.message().size() + 1;


    return current_alignment - initial_alignment;
}

void power::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_freq;
    scdr << m_message.c_str();

}

void power::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_freq;
    dcdr >> m_message;
}

/*!
 * @brief This function sets a value in member freq
 * @param _freq New value for member freq
 */
void power::freq(
        uint32_t _freq)
{
    m_freq = _freq;
}

/*!
 * @brief This function returns the value of member freq
 * @return Value of member freq
 */
uint32_t power::freq() const
{
    return m_freq;
}

/*!
 * @brief This function returns a reference to member freq
 * @return Reference to member freq
 */
uint32_t& power::freq()
{
    return m_freq;
}

/*!
 * @brief This function copies the value in member message
 * @param _message New value to be copied in member message
 */
void power::message(
        const std::string& _message)
{
    m_message = _message;
}

/*!
 * @brief This function moves the value in member message
 * @param _message New value to be moved in member message
 */
void power::message(
        std::string&& _message)
{
    m_message = std::move(_message);
}

/*!
 * @brief This function returns a constant reference to member message
 * @return Constant reference to member message
 */
const std::string& power::message() const
{
    return m_message;
}

/*!
 * @brief This function returns a reference to member message
 * @return Reference to member message
 */
std::string& power::message()
{
    return m_message;
}


size_t power::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return power_max_key_cdr_typesize;
}

bool power::isKeyDefined()
{
    return false;
}

void power::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

